dist: trusty
sudo: true
git:
    submodules: false
language: cpp
os:
    - linux
compiler:
    - gcc
before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' -y ;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get update;fi
install:
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo apt-get install -qq g++-7;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get install python-dev -y;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get install -qq libboost-all-dev;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang  clang  /usr/bin/clang-3.5  90 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-3.5;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then a=$(sudo find / -name llvm-cov | grep 3.5 | head -1);sudo ln -s ${a} /usr/bin/llvm-cov;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then a=$(sudo find / -name llvm-cov | grep 3.4 | head -1);sudo mv ${a} ${a}.old;fi
    - if [ "$TRAVIS_OS_NAME" == "osx"   -a "$CXX" == "clang++" ]; then sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-cov /usr/local/bin/llvm-cov; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then wget -O boost_1_56.tar.gz http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.gz/download;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then tar xzf boost_1_56.tar.gz;cd boost_1_56_0/;mkdir -p /tmp/extra;./bootstrap.sh --prefix=/tmp/extra;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then ./b2 cxxflags="-Wno-strict-aliasing -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-placement-new" --with-system --with-context --with-coroutine;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo ./b2 --with-system --with-context --with-coroutine install | awk 'NR == 1 || NR % 25 == 0';fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then cd ..;fi
before_script:
    - mv .gitmodules gitmodules.old
    - sed -e 's#git@\([^:]*\):#https://\1/#' gitmodules.old > .gitmodules
script:
    - ./configure --with-boost=/tmp/extra --with-thor-build-on-travis --disable-binary
    - export PATH=${PATH}:$(pwd)/build/bin;make 
after_success:
    - ./uploadcodecovrage
branches:
  only:
      - master
      - /^feature-.*$/
      - /^version-.*$/
